eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
okta:
  oauth2:
    issuer: https://dev-56986490.okta.com/oauth2/default
    audience: api://default
    client-id: 0oadpahd6mHnrmpgw5d7
    client-secret: eI2THAvlUfCzwaezyagi2HUOQ1H7KccHgUTfLjF6NHuMrfZmHdyowcP4rmqF_SDq
    scopes: openid, email, profile, offline_access
    
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
